<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>
	<groupId>org.pih.openmrs</groupId>
	<artifactId>pihmalawi-emr</artifactId>
	<version>9.2.0-SNAPSHOT</version>
	<packaging>pom</packaging>
	<name>PIH Malawi EMR</name>
	<description>PIH Malawi EMR parent</description>
	<url>https://github.com/PIH/pihmalawi-emr</url>

	<organization>
		<name>Partners In Health</name>
		<url>http://pih.org</url>
	</organization>

	<developers>
		<developer>
			<name>Partners In Health</name>
		</developer>
	</developers>

	<licenses>
		<license>
			<name>Mozilla Public License 2.0 with Healthcare Disclaimer</name>
			<url>http://openmrs.org/license</url>
		</license>
	</licenses>

	<scm>
		<connection>scm:git:https://github.com/PIH/pihmalawi-emr.git</connection>
		<developerConnection>scm:git:https://github.com/PIH/pihmalawi-emr.git</developerConnection>
		<url>https://github.com/PIH/pihmalawi-emr/</url>
	  <tag>HEAD</tag>
  	</scm>

	<properties>
		<openMRSVersion>2.8.7</openMRSVersion>
		<addresshierarchyVersion>3.0.0-SNAPSHOT</addresshierarchyVersion>
		<appframeworkVersion>2.19.0</appframeworkVersion>
		<appuiVersion>1.18.0</appuiVersion>
		<authenticationVersion>2.5.0-SNAPSHOT</authenticationVersion>
		<authenticationuiVersion>1.3.0</authenticationuiVersion>
		<calculationVersion>2.0.0</calculationVersion>
		<coreappsVersion>3.4.0</coreappsVersion>
		<emrapiVersion>3.4.0</emrapiVersion>
		<eventVersion>4.0.0</eventVersion>
		<fhir2Version>4.2.0</fhir2Version>
		<htmlformentryVersion>7.3.0-SNAPSHOT</htmlformentryVersion>
		<htmlformentryuiVersion>3.3.0-SNAPSHOT</htmlformentryuiVersion>
		<htmlwidgetsVersion>2.0.1</htmlwidgetsVersion>
		<idgenVersion>5.0.4</idgenVersion>
		<initializerVersion>2.12.0</initializerVersion>
		<legacyuiVersion>2.2.0</legacyuiVersion>
		<metadatamappingVersion>2.0.0</metadatamappingVersion>
		<namephoneticsVersion>1.20.0-SNAPSHOT</namephoneticsVersion>
		<owaVersion>1.16.0-SNAPSHOT</owaVersion>
		<registrationappVersion>1.29.0</registrationappVersion>
		<registrationcoreVersion>1.13.0</registrationcoreVersion>
		<reportingcompatibilityVersion>2.11.0</reportingcompatibilityVersion>
		<reportingVersion>2.1.0</reportingVersion>
		<reportingrestVersion>2.0.0</reportingrestVersion>
		<reportinguiVersion>1.14.0</reportinguiVersion>
		<serializationxstreamVersion>0.3.0</serializationxstreamVersion>
		<spaVersion>3.0.0</spaVersion>
		<testutilsVersion>1.7.0</testutilsVersion>
		<uicommonsVersion>3.1.0</uicommonsVersion>
		<uiframeworkVersion>4.0.0</uiframeworkVersion>
		<uilibraryVersion>2.0.7</uilibraryVersion>
		<webservicesRestVersion>3.4.1</webservicesRestVersion>
		<sdkVersion>6.9.0-SNAPSHOT</sdkVersion>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.javadoc.failOnError>false</maven.javadoc.failOnError>
	</properties>

	<modules>
		<module>api</module>
		<module>omod</module>
		<module>content</module>
        <module>distro</module>
	</modules>

	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.openmrs.maven.plugins</groupId>
					<artifactId>openmrs-sdk-maven-plugin</artifactId>
					<version>${sdkVersion}</version>
				</plugin>
				<plugin>
					<artifactId>maven-resources-plugin</artifactId>
					<version>3.5.0</version>
					<configuration>
						<encoding>UTF-8</encoding>
						<includeEmptyDirs>true</includeEmptyDirs>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-assembly-plugin</artifactId>
					<version>3.8.0</version>
				</plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-release-plugin</artifactId>
                    <version>3.2.0</version>
                    <configuration>
                        <tagNameFormat>@{project.version}</tagNameFormat>
                        <projectVersionPolicyId>SemVerVersionPolicy</projectVersionPolicyId>
                        <arguments>-DskipTests</arguments>
                    </configuration>
                </plugin>
				<plugin>
					<groupId>org.codehaus.mojo</groupId>
					<artifactId>versions-maven-plugin</artifactId>
                    <version>2.16.0</version>
					<configuration>
						<generateBackupPoms>false</generateBackupPoms>
						<excludeProperties>sdkVersion</excludeProperties>
						<properties>
							<property>
								<name>openMRSVersion</name>
								<version>[2.8.0,2.8.999)</version>
							</property>
						</properties>
					</configuration>
				</plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-javadoc-plugin</artifactId>
                    <version>2.10.3</version>
                </plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
					<configuration>
						<target>1.8</target>
						<source>1.8</source>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.openmrs.maven.plugins</groupId>
					<artifactId>maven-openmrs-plugin</artifactId>
					<version>1.0.1</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-dependency-plugin</artifactId>
					<version>2.4</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-surefire-plugin</artifactId>
					<version>2.22.1</version>
					<configuration>
						<parallel>false</parallel>
						<!-- Some tests are locale specific -->
						<argLine>-Duser.language=en -Duser.region=US</argLine>
					</configuration>
				</plugin>

				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-jar-plugin</artifactId>
					<executions>
						<execution>
							<goals>
								<goal>test-jar</goal>
							</goals>
						</execution>
					</executions>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>

	<distributionManagement>
		<repository>
			<id>openmrs-repo-modules-pih</id>
			<name>Modules</name>
            <url>https://openmrs.jfrog.io/artifactory/modules-pih/</url>
		</repository>
		<snapshotRepository>
			<id>openmrs-repo-modules-pih</id>
			<name>OpenMRS Snapshots</name>
			<url>https://openmrs.jfrog.io/artifactory/modules-pih-snapshots</url>
		</snapshotRepository>
	</distributionManagement>

	<repositories>
		<repository>
			<id>openmrs-repo</id>
			<name>OpenMRS Nexus Repository</name>
			<url>https://openmrs.jfrog.io/artifactory/public</url>
		</repository>
		<repository>
			<name>Central Portal Snapshots</name>
			<id>central-portal-snapshots</id>
			<url>https://central.sonatype.com/repository/maven-snapshots/</url>
			<releases>
				<enabled>false</enabled>
			</releases>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
		<repository>
			<id>mks-repo</id>
			<name>Mekom Solutions Maven repository</name>
			<url>https://nexus.mekomsolutions.net/repository/maven-public</url>
		</repository>
	</repositories>

	<pluginRepositories>
		<pluginRepository>
			<id>openmrs-repo</id>
			<name>OpenMRS Nexus Repository</name>
			<url>https://openmrs.jfrog.io/artifactory/public</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</pluginRepository>
		<pluginRepository>
			<id>openmrs-repo-snapshots</id>
			<name>OpenMRS Snapshots Repo</name>
			<url>https://openmrs.jfrog.io/artifactory/snapshots</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </pluginRepository>
        <pluginRepository>
            <id>mks-repo</id>
            <name>Mekom Solutions Maven repository</name>
            <url>https://nexus.mekomsolutions.net/repository/maven-public</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</pluginRepository>
	</pluginRepositories>

</project>
