package org.openmrs.module.pihmalawi.models;

public class YendaNafePatientRegistrationModel {
    public String _id;
    public String type;
    public String name;
    public String sex;
    public String date_of_birth;
    public String knows_dob;
    public String art_start_date;
    public String tb_treatment_start_date;
    public String primary_phone_number;
    public String secondary_phone_number;
    public String conditions;
    public String conditions_other;
    public String malnutrition_program;
    public String ncds;
    public String ncds_other;
    public String mental_health_type;
    public String mental_health_type_other;
    public String eid_emr_id_source;
    public String eid_emr_id_source_other;
    public String art_emr_id_source;
    public String art_emr_id_source_other;
    public String ncd_emr_id_source;
    public String ncd_emr_id_source_other;
    public String eid_id;
    public String art_id;
    public String ncd_id;
    public String notes;
    public String reported_date;
    public String patient_id;
    public String contact_type;
    public String chw;
    public String traditional_authority;
    public String village;
    public String health_surveillance_assistant;
    public String site;
    public String location_uuid;

    public YendaNafePatientRegistrationModel()
    {
        this._id = "";
        this.type = "";
        this.name = "";
        this.sex = "";
        this.date_of_birth = "";
        this.knows_dob = "";
        this.art_start_date = "";
        this.tb_treatment_start_date = "";
        this.primary_phone_number = "";
        this.secondary_phone_number = "";
        this.conditions = "";
        this.conditions_other = "";
        this.malnutrition_program = "";
        this.ncds = "";
        this.ncds_other = "";
        this.mental_health_type = "";
        this.mental_health_type_other = "";
        this.eid_emr_id_source = "";
        this.eid_emr_id_source_other = "";
        this.art_emr_id_source = "";
        this.art_emr_id_source_other = "";
        this.ncd_emr_id_source = "";
        this.ncd_emr_id_source_other = "";
        this.eid_id = "";
        this.art_id = "";
        this.ncd_id = "";
        this.notes = "";
        this.reported_date = "";
        this.patient_id = "";
        this.contact_type = "";
        this.chw = "";
        this.traditional_authority = "";
        this.village = "";
        this.health_surveillance_assistant = "";
        this.site = "";
        this.location_uuid = "";
    }
}
