<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.pih.openmrs</groupId>
        <artifactId>pihmalawi-emr</artifactId>
        <version>9.2.0-SNAPSHOT</version>
    </parent>

    <artifactId>pihmalawi-distro</artifactId>
    <packaging>jar</packaging>
    <name>PIH Malawi EMR Distribution</name>
    <description>Distro project for PIH Malawi EMR</description>

    <properties>
        <frontendVersion>1.46.0-SNAPSHOT</frontendVersion>
        <pwaApzuIc3Version>2.0.0-SNAPSHOT</pwaApzuIc3Version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.openmrs.module</groupId>
            <artifactId>pihmalawi-omod</artifactId>
            <version>${project.parent.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.pih.openmrs</groupId>
            <artifactId>pihmalawi-content</artifactId>
            <version>${project.parent.version}</version>
            <type>zip</type>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.pih.openmrs</groupId>
            <artifactId>openmrs-frontend-pihemr</artifactId>
            <version>${frontendVersion}</version>
            <type>zip</type>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.pih.openmrs</groupId>
            <artifactId>pwa-apzu-ic3</artifactId>
            <version>${pwaApzuIc3Version}</version>
            <type>zip</type>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <!-- Add the openmrs-distro.properties file into the artifact jar and apply variable replacements -->
            <plugin>
                <artifactId>maven-resources-plugin</artifactId>
                <configuration>
                    <propertiesEncoding>UTF-8</propertiesEncoding>
                    <resources>
                        <resource>
                            <directory>${basedir}</directory>
                            <filtering>true</filtering>
                            <includes>
                                <include>openmrs-distro.properties</include>
                            </includes>
                        </resource>
                    </resources>
                    <outputDirectory>${project.build.directory}/classes</outputDirectory>
                </configuration>
            </plugin>

            <!-- Use the SDK to retrieve all artifacts defined in openmrs-distro.properties -->
            <plugin>
                <groupId>org.openmrs.maven.plugins</groupId>
                <artifactId>openmrs-sdk-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>build-distro</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>build-distro</goal>
                        </goals>
                        <configuration>
                            <distro>${project.build.directory}/classes/openmrs-distro.properties</distro>
                            <dir>${project.build.directory}/distro</dir>
                            <skipDockerCompose>true</skipDockerCompose>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>distro-zip</id>
            <build>
                <plugins>
                    <!-- Assemble artifacts into a zip artifact -->
                    <plugin>
                        <artifactId>maven-assembly-plugin</artifactId>
                        <configuration>
                            <appendAssemblyId>false</appendAssemblyId>
                            <descriptors>
                                <descriptor>${basedir}/assembly.xml</descriptor>
                            </descriptors>
                        </configuration>
                        <executions>
                            <execution>
                                <id>make-assembly</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>single</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

</project>
